spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**
    discovery:
      enabled: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: http://zipkin:9411/api/v2/spans
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

